###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-09-30 12:53:09
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-11-03 17:38:04
###############################################################


invokables:
	eligibility_data_fieldset_form : Data/Form/EligibilityDataFieldsetForm
	eligibility_data_create_form : Data/Form/EligibilityDataCreateForm
	eligibility_data_edit_form : Data/Form/EligibilityDataEditForm
	eligibility_data_search_form : Data/Form/EligibilityDataSearchForm